# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            StatefulJ
tagline:          ''
description:      'State Machines made easy'
url:              http://statefulj.io 
baseurl:          ''

author:
  name:           'Andrew Hall'
  url:            https://twitter.com/developfwd

paginate:         5

# Custom vars
version:          3.0

github:
  repo:           https://github.com/statefulj
