# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            StatefulJ
tagline:          ''
description:      'Making State Machines your friend'
url:              http://hyde.getpoole.com 
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.3

github:
  repo:           https://github.com/poole/hyde
