# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            StatefulJ
tagline:          ''
description:      'State Machines made easy'
url:              http://hyde.getpoole.com 
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.9

github:
  repo:           https://github.com/poole/hyde
