# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            StatefulJ
tagline:          ''
description:      'State Machines made easy'
url:              http://statefulj.org 
baseurl:          /

author:
  name:           'Andrew Hall'
  url:            https://twitter.com/developfwd

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/statefulj
