# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            StatefulJ
tagline:          ''
description:      'State Machines made easy'
url:              http://statefulj.org 
baseurl:          /

author:
  name:           'Andrew Hall'
  url:            https://twitter.com/developfwd

paginate:         5

# Custom vars
version:          1.0.7

github:
  repo:           https://github.com/statefulj
